name: regional-mom6
channels:
  - conda-forge
dependencies:
  - dask
  - netcdf4
  - pydap
  - zarr=2.18.3
  - kerchunk
  - fsspec
  - s3fs
  - gcsfs
  - python=3.11
  - xarray
  - xesmf
  - pytest
  - beautifulsoup4
  - matplotlib
  - pip
  - pip:
    - rmom6-preprocessing
  
  
