name: regional-mom6
channels:
  - conda-forge
dependencies:
  - dask
  - netcdf4
  - pydap
  - zarr
  - fsspec
  - s3fs
  - gcsfs
  - python=3.11
  - xarray
  - xesmf
  - pytest
  - beautifulsoup4
  - matplotlib
