name: regional-mom6-dev
channels:
  - conda-forge
dependencies:
  - dask
  - netcdf4
  - pydap
  - zarr=2.18.3
  - kerchunk
  - fsspec
  - s3fs
  - gcsfs
  - python=3.11
  - xarray
  - xesmf
  - prefect
  - pytest
  - beautifulsoup4
  - matplotlib
  - jupyter-book
  - sphinx
  - sphinx-autodoc-typehints
  - sphinxcontrib-napoleon
  - pip
  - pip:
    - build
    - twine

