"""
The script do a batch reorganiztion of the yearly files
that is generated by Jessie and convert them to single
varible files with the entire time period
"""
import os
import gc
from glob import glob
import xarray as xr

if __name__ == "__main__":
    # original data path
    ORI_PATH = '/Projects/CEFI/private/scratch/chsu/NEP_hindcast_v2_kelly'

    # original file pattern
    ORI_FILE = 'ice_daily.????????-????????.siconc.nc'

    # output data path
    OUT_PATH = '/Projects/CEFI/private/scratch/chsu/NEP_hindcast_v2_kelly'

    # output file pattern
    OUT_FILE = 'ice_daily.iYYYYMM-fYYYYMM.VAR.nc'

    # get all the file list from the original path
    ori_files = glob(os.path.join(ORI_PATH, ORI_FILE))
    # sort the files by name
    ori_files = sorted(ori_files)

    # lazy load all the original yearly files
    ds_ori = xr.open_mfdataset(ori_files, combine='by_coords',chunks={'time': 1})

    # get all the variables in the dataset
    variables = list(ds_ori.data_vars)
    coords = list(ds_ori.coords)
    coords += [
        'average_T1',
        'average_T2',
        'average_DT',
        'time_bnds'
    ]

    # get the initial and final year
    initial_year = int(ds_ori.time.dt.year.data[0])
    initial_month = int(ds_ori.time.dt.month.data[0])
    iYYYYMM = f'{initial_year:04d}{initial_month:02d}'
    final_year = int(ds_ori.time.dt.year.data[-1])
    final_month = int(ds_ori.time.dt.month.data[-1])
    fYYYYMM = f'{final_year:04d}{final_month:02d}'
    OUT_FILE = OUT_FILE.replace('iYYYYMM', iYYYYMM)
    OUT_FILE = OUT_FILE.replace('fYYYYMM', fYYYYMM)

    for var in variables:
        if var not in coords:
            # get output file name
            OUT_FILE = OUT_FILE.replace('VAR', var)

            ds_out = ds_ori[var].to_dataset(name=var).load()
            ds_out.to_netcdf(
                os.path.join(OUT_PATH, OUT_FILE),
                mode='w',
                format='NETCDF4',
                unlimited_dims='time'
            )
            print(f'Converted {var} to {OUT_FILE}')
            del ds_out
            gc.collect()

    # close the dataset
    ds_ori.close()
    print('All variables converted successfully.')
    print(f'Output files are saved in {OUT_PATH}')
    print(f'Initial year: {initial_year}, Final year: {final_year}')