"""
The script do a batch reorganiztion of the yearly files
that is generated by Jessie and convert them to single
varible files with the entire time period
"""
import os
from glob import glob
import xarray as xr
 

if __name__ == "__main__":
    # original data path
    ORI_PATH = '/Projects/CEFI/private/scratch/jliu/NEP10k_COBALT_92-93_spinup_new_relax_ts/'

    # original file pattern
    ORI_FILE = 'YYYY0101.ocean_cobalt_tracers_month_z.nc'

    # patch data path
    OUT_PATH = '/Projects/CEFI/regional_mom6/cefi_portal/northeast_pacific/full_domain/hindcast/monthly/raw/r20250509'

    # patch data path
    OUT_PATH2 = '/Projects/CEFI/regional_mom6/cefi_portal/northeast_pacific/full_domain/hindcast/monthly/regrid/r20250509'

    # change YYYY iin ori file to ????
    ORI_FILE = ORI_FILE.replace('YYYY', '????')

    # get all the file list from the original path
    ori_files = glob(os.path.join(ORI_PATH, ORI_FILE))
    # sort the files by name
    ori_files = sorted(ori_files)

    # lazy load all the original yearly files
    ds_ori = xr.open_mfdataset(ori_files, combine='by_coords',chunks={'time': 1})

    # based on Liz's suggestion to use only till end of 2024
    ds_ori = ds_ori.sel(time=slice('1993-01-01', '2024-12-31'))

    # get all the variables in the dataset
    variables = list(ds_ori.data_vars)
    coords = list(ds_ori.coords)
    coords += [
        'average_T1',
        'average_T2',
        'average_DT',
        'time_bnds'
    ]

    for var in variables:
        if var not in coords:
            # find files in the patch directory
            patch_files = glob(os.path.join(
                OUT_PATH, f'{var}.nep.full.hcast.monthly.raw.r20250509.199301-202412.nc'
                )
            )

            if len(patch_files) != 1:
                print(f'Error: {len(patch_files)} files found for variable {var} in {OUT_PATH}')
                pass
            else:
                # remove the file
                os.remove(patch_files[0])
                print(f'Removed {patch_files[0]}')

            # # test if only one file is found
            # if len(patch_files) != 1:
            #     print(f'Error: {len(patch_files)} files found for variable {var} in {OUT_PATH}')
            #     continue
            # with xr.open_dataset(patch_files[0]) as ds:
            #     ds = ds.load()
            # ds.attrs['cefi_ori_filename'] = f"ocean_cobalt_tracers_month_z.199301-202412.{var}.nc"
            # ds.attrs['cefi_ori_category'] = "ocean_cobalt_tracers_month_z"
            # ds.to_netcdf(patch_files[0], mode='w')

            
            # find files in the patch directory
            patch_files2 = glob(os.path.join(
                OUT_PATH2, f'{var}.nep.full.hcast.monthly.regrid.r20250509.199301-202412.nc'
                )
            )

            if len(patch_files2) != 1:
                print(f'Error: {len(patch_files2)} files found for variable {var} in {OUT_PATH2}')
                pass
            else:
                # remove the file
                os.remove(patch_files2[0])
                print(f'Removed {patch_files2[0]}')