name: PR pytest checking

on:
  pull_request:
     branches:
       - develop
       - main
     paths:
       - './'

jobs:
  checking_json:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Micromamba ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: regional_mom6.yml
          init-shell: bash

      - name: pytesting
        shell: bash -l {0}
        run: pytest