name: PR pytest checking

on:
  pull_request:
    branches:
      - develop

jobs:
  checking_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: regional_mom6.yml
          init-shell: bash

      - name: pytesting
        shell: bash -l {0}
        run: pytest