name: PR unittest

on: 
  pull_request:
    branches:
      - develop
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash

      - name: pytesting
        shell: bash -l {0}
        run: pytest --location opendap