name: unittest

on:
  push:
    branches:
      - main    

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash

      - name: Setup package config file
        shell: bash -l {0}
        run: cp config.json.template config.json

      - name: pytesting
        shell: bash -l {0}
        run: pytest --location opendap